services:
  server:
    build: .
    ports:
      - '3847:3847'
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GH_MONIT_USER=${GH_MONIT_USER:-}
      - GH_MONIT_ORG=${GH_MONIT_ORG:-}
      - GH_MONIT_REFRESH_SCHEDULE=${GH_MONIT_REFRESH_SCHEDULE:-0 6 * * *}
    volumes:
      - gh-monit-data:/data
    restart: unless-stopped

volumes:
  gh-monit-data:
